version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
    - "9411:9411"
    networks:
    - goshuttle-tracing
  go-shuttle-test:
    image: ${IMAGE}:latest
    command: ["-run", "TestConnectionString/TestPublishAndListenNotRenewingLock", "-tags", "debug"]
#    command: ["-run", "TestConnectionString", "-tags", "debug"]
    env_file:
    - .env
    environment:
    - TRACING=1
    - JAEGER_AGENT_HOST=jaeger
    - JAEGER_AGENT_PORT=6831
    - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    - JAEGER_SAMPLER_ENDPOINT=http://jaeger:5778/sampling
    - JAEGER_SAMPLER_TYPE=const
    - JAEGER_SAMPLER_PARAM=1
    - JAEGER_SERVICE_NAME=go-shuttle-test
    - DEBUG-LEVEL=3
    networks:
    - goshuttle-tracing
    depends_on:
    - jaeger

networks:
  goshuttle-tracing:
