# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- bash: az login --service-principal -u "${CLIENT_ID}" -p "${CLIENT_SECRET}" --tenant "${TENANT_ID}" --output none
  env:
    CLIENT_ID: $(INT_CLIENT_ID)
    CLIENT_SECRET: $(INT_CLIENT_SECRET)
    TENANT_ID: $(INT_TENANT_ID)
  displayName: 'az login'

- script: az account show
  displayName: 'az account show'