# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- bash: az login --service-principal -u "${CLIENT_ID}" -p "${CLIENT_SECRET}" --tenant "${TENANT_ID}" --output none
  env:
    CLIENT_ID: $(INT_CLIENT_ID)
    CLIENT_SECRET: $(INT_CLIENT_SECRET)
    TENANT_ID: $(INT_TENANT_ID)
  displayName: 'az login'

- bash: |
      echo "SERVICEBUS_NAMESPACE_NAME: ${SERVICEBUS_NAMESPACE_NAME}" >> .env
      echo "TEST_LOCATION: ${LOCATION}" >> .env
      echo "TEST_RESOURCE_GROUP: ${RESOURCE_GROUP}" >> .env
      echo "REGISTRY_NAME: ${REGISTRY_NAME}" >> .env
      echo "AZURE_CLIENT_ID: ${CLIENT_ID}" >> .env
      echo "AZURE_CLIENT_SECRET: ${CLIENT_SECRET}" >> .env
      echo "AZURE_TENANT_ID: ${TENANT_ID}" >> .env
      echo "AZURE_SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}" >> .env
      make test-setup
  displayName: setup environment
  env:
    SERVICEBUS_NAMESPACE_NAME: $(TEST_SERVICEBUS_NAMESPACE)
    LOCATION: $(TEST_LOCATION)
    RESOURCE_GROUP: $(TEST_RESOURCE_GROUP)
    REGISTRY_NAME: $(TEST_REGISTRY_NAME)
    CLIENT_ID: $(INT_CLIENT_ID)
    CLIENT_SECRET: $(INT_CLIENT_SECRET)
    TENANT_ID: $(INT_TENANT_ID)
    SUBSCRIPTION_ID: $(INT_SUBSCRIPTION_ID)

- bash: make integration
  displayName: run integration
