# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration-tests:
    environment: Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.JSON_CREDS }}
    - name: setup environment
      shell: bash
      run: |
        echo "${{ secrets.ENV }}" > .env
        make test-setup
    - name: Dotenv Action
      uses: falti/dotenv-action@v0.2.5
      with:
        path: .env
    - name: run integration
      shell: bash
      run: make integration
