name: Build and Unit Tests for v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: |
          cd v2
          go build -v ./...

      - name: Unit Tests
        run: |
          cd v2
          go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: v2
          args: --print-issued-lines=true --path-prefix string
