name: Build and Unit Tests for v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          cd v2
          go build -v ./...

      - name: Unit Tests
        run: |
          cd v2
          go test -v -coverprofile=../.coverage/profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: .coverage/profile.cov
